"""orders and xsm tables

Revision ID: 0001
Revises:
Create Date: 2026-09-29 20:28:42.359502

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer", sa.String(length=120), nullable=False),
        sa.Column(
            "statechart",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            nullable=True,
        ),
        sa.Column("statechart_state", sa.String(length=512), nullable=True),
        sa.Column("statechart_state_ids", sa.JSON(), nullable=True),
        sa.Column("statechart_version", sa.Integer(), nullable=False),
        sa.Column(
            "statechart_machine_version", sa.String(length=255), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_orders_statechart_state"),
        "orders",
        ["statechart_state"],
        unique=False,
    )
    op.create_table(
        "xsm_deadlines",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source", sa.String(length=255), nullable=False),
        sa.Column("key", sa.String(length=200), nullable=False),
        sa.Column("state_id", sa.String(length=512), nullable=False),
        sa.Column("entry_seq", sa.Integer(), nullable=False),
        sa.Column("due_at_wall", sa.Float(), nullable=False),
        sa.Column("delay_ms", sa.BigInteger(), nullable=False),
        sa.Column("event_type", sa.String(length=512), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "xsm_deadlines_due", "xsm_deadlines", ["due_at_wall"], unique=False
    )
    op.create_index(
        "xsm_deadlines_key", "xsm_deadlines", ["source", "key"], unique=False
    )
    op.create_table(
        "xsm_inbox",
        sa.Column("scope", sa.String(length=400), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("fingerprint", sa.String(length=128), nullable=False),
        sa.Column("receipt", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("scope", "key"),
    )
    op.create_index("xsm_inbox_exp", "xsm_inbox", ["expires_at"], unique=False)
    op.create_table(
        "xsm_locks",
        sa.Column("source", sa.String(length=255), nullable=False),
        sa.Column("key", sa.String(length=200), nullable=False),
        sa.Column("owner", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("source", "key"),
    )
    op.create_table(
        "xsm_schema",
        sa.Column("component", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("component"),
    )
    op.create_table(
        "xsm_snapshots",
        sa.Column("key", sa.String(length=200), nullable=False),
        sa.Column("snapshot", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("machine_version", sa.String(length=255), nullable=False),
        sa.Column("updated_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "xsm_transitions",
        sa.Column("machine_id", sa.String(length=255), nullable=False),
        sa.Column("seq", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("ts", sa.Float(), nullable=False),
        sa.Column("record", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("machine_id", "seq"),
    )
    op.create_index(
        "xsm_transitions_ts", "xsm_transitions", ["ts"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("xsm_transitions_ts", table_name="xsm_transitions")
    op.drop_table("xsm_transitions")
    op.drop_table("xsm_snapshots")
    op.drop_table("xsm_schema")
    op.drop_table("xsm_locks")
    op.drop_index("xsm_inbox_exp", table_name="xsm_inbox")
    op.drop_table("xsm_inbox")
    op.drop_index("xsm_deadlines_key", table_name="xsm_deadlines")
    op.drop_index("xsm_deadlines_due", table_name="xsm_deadlines")
    op.drop_table("xsm_deadlines")
    op.drop_index(op.f("ix_orders_statechart_state"), table_name="orders")
    op.drop_table("orders")
    # ### end Alembic commands ###
