"""xsm_outbox: the transactional outbox table (#293)

`SQLAlchemyOutboxStore` writes order.paid events here in the same
transaction as the order row; `python sync_app.py relay` drains it.
Autogenerated on top of 0001 after `xsm_sqlalchemy_ddl` started
including the table.

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-07 07:39:32.873359

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: Union[str, Sequence[str], None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "xsm_outbox",
        sa.Column("seq", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("topic", sa.String(length=255), nullable=False),
        sa.Column("subject", sa.String(length=200), nullable=True),
        sa.Column("envelope", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("sent_at", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("seq"),
    )
    op.create_index(
        "xsm_outbox_pending", "xsm_outbox", ["sent_at", "seq"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("xsm_outbox_pending", table_name="xsm_outbox")
    op.drop_table("xsm_outbox")
    # ### end Alembic commands ###
