"""xsm_outbox: relay lease columns (#293 battle)

Several relays may drain one outbox: `OutboxRelay` leases the rows it is
publishing (`claimed_by`, `claimed_until`) so two replicas never publish
the same row at once. Autogenerated on top of 0002 after the library
added the columns to `xsm_outbox`.

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-09 02:40:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: Union[str, Sequence[str], None] = "0002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "xsm_outbox",
        sa.Column("claimed_by", sa.String(length=128), nullable=True),
    )
    op.add_column(
        "xsm_outbox", sa.Column("claimed_until", sa.Float(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("xsm_outbox", "claimed_until")
    op.drop_column("xsm_outbox", "claimed_by")
    # ### end Alembic commands ###
