# Generated by Django 6.1.1 -- the `xsm_django` app's tables (#280).

from typing import Any, List

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: List[Any] = []

    operations = [
        migrations.CreateModel(
            name="StatechartDeadline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=128)),
                ("key", models.CharField(max_length=200)),
                ("state_id", models.CharField(max_length=512)),
                ("entry_seq", models.IntegerField()),
                ("due_at_wall", models.FloatField()),
                ("delay_ms", models.BigIntegerField()),
                ("event_type", models.CharField(max_length=600)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["source", "due_at_wall"],
                        name="xsm_deadline_due",
                    ),
                    models.Index(
                        fields=["source", "key"], name="xsm_deadline_key"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StatechartLock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=128)),
                ("key", models.CharField(max_length=200)),
                ("owner", models.CharField(max_length=64)),
                ("expires_at", models.FloatField()),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "key"), name="xsm_lock_source_key"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StatechartSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=128)),
                ("key", models.CharField(max_length=200)),
                ("snapshot", models.TextField()),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "machine_version",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("updated_at", models.FloatField()),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "key"),
                        name="xsm_snapshot_source_key",
                    )
                ],
            },
        ),
    ]
