# Generated by Django (#281).

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("xsm_django", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OutboxMessage",
            fields=[
                (
                    "seq",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("message_id", models.CharField(max_length=64)),
                ("topic", models.CharField(max_length=255)),
                (
                    "subject",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("envelope", models.TextField()),
                ("created_at", models.FloatField()),
                ("sent_at", models.FloatField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["sent_at", "seq"], name="xsm_outbox_pending"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TransitionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.CharField(max_length=64)),
                ("seq", models.PositiveIntegerField()),
                ("event", models.CharField(max_length=255)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("from_states", models.JSONField(blank=True, default=list)),
                ("to_states", models.JSONField(blank=True, default=list)),
                ("actions", models.JSONField(blank=True, default=list)),
                (
                    "disposition",
                    models.CharField(default="transition", max_length=16),
                ),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "correlation_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "machine_version",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["content_type", "object_id", "seq"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="xsm_log_object",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("content_type", "object_id", "seq"),
                        name="xsm_transitionlog_seq",
                    )
                ],
            },
        ),
    ]
