# Generated by Django (#283).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("xsm_django", "0002_outboxmessage_transitionlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdempotencyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scope", models.CharField(max_length=400)),
                ("key", models.CharField(max_length=200)),
                ("fingerprint", models.CharField(max_length=64)),
                ("receipt_json", models.TextField(blank=True, null=True)),
                ("expires_at", models.FloatField(blank=True, null=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scope", "key"), name="xsm_idem_scope_key"
                    )
                ],
            },
        ),
    ]
