# Generated by Django.

import xstate_statemachine.contrib.django.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "statechart",
                    xstate_statemachine.contrib.django.fields.StatechartField(),
                ),
                (
                    "statechart_state",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=512,
                        null=True,
                    ),
                ),
                (
                    "statechart_state_ids",
                    models.JSONField(blank=True, editable=False, null=True),
                ),
                (
                    "statechart_version",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                (
                    "statechart_machine_version",
                    models.CharField(
                        blank=True, editable=False, max_length=255, null=True
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
