# tests/tests_cli/test_battle_279_codegen.py
"""#279 battle: the codegen companions a team checks in and edits.

`xsm gt --with-api --with-models` emits a FastAPI router and pydantic
models a team owns. Those files are a verified STARTING POINT -- so what
is verified must be true for every chart, the output must be stable
under regeneration, and the generated router must have the registry's
guarantees, not a lookalike. Pinned, in-process (no 2.4 s subprocess per
chart):

* **the whole corpus** -- every chart that generates yields `_api.py` /
  `_models.py` that `ast.parse`, import, mount on a `FastAPI()` and
  produce an OpenAPI document with one route per declared event (the
  deliberate refusals -- a chart with no states -- are named, not
  silent); charts whose ids collide produce the same filename, which
  `--check` must report rather than silently overwrite;
* **byte-stable regeneration** -- generating twice is identical (modulo
  the provenance banner's timestamp/version line), `--check` is exit 0,
  adding an event flips `--check` to 1 and `--diff` names the route;
* **the generated router keeps the registry's rules** -- a per-event
  `authorize` denial is a 403 that saves NOTHING (the version does not
  bump; a refused request must not make a concurrent writer lose with
  409), `Idempotency-Key` without an inbox is 501, an unknown event
  route is 404, the `authorize` stub RAISES until implemented (X0.1);
* **odd names** -- event types with spaces / `:` / `!` / `/` / unicode
  slug into unique URL segments and unique `operationId`s; two events
  that slug identically are refused at generation, not merged;
* **Windows** -- an output directory with spaces and unicode; CRLF-safe
  files; `--plain` output has no mojibake;
* **performance** -- in-process generation of a 50-event chart in
  bounded time; `--check` over the corpus does not re-import or
  re-verify when nothing changed.
"""

from __future__ import annotations

import ast
import importlib
import io
import json
import logging
import pathlib
import sys
import tempfile
import time
from contextlib import redirect_stdout
from typing import Any, Dict, List, Tuple

import pytest

pytest.importorskip("fastapi")
pytest.importorskip("httpx")
pytest.importorskip("pydantic")

from src.xstate_statemachine.cli.__main__ import main  # noqa: E402
from src.xstate_statemachine.cli.utils import (  # noqa: E402
    camel_to_snake,
    module_safe_name,
)

ROOT = pathlib.Path(__file__).resolve().parents[2]
CORPUS = ROOT / "tests" / "tests_cli" / "stately_machines"

pytestmark = pytest.mark.timeout(600)


def _run(argv: List[str]) -> Tuple[int, str]:
    saved, sys.argv = sys.argv, ["xsm", *argv]
    buf = io.StringIO()
    logging.disable(logging.CRITICAL)
    try:
        with redirect_stdout(buf):
            main()
        code = 0
    except SystemExit as exc:
        code = int(exc.code or 0)
    finally:
        sys.argv = saved
        logging.disable(logging.NOTSET)
    return code, buf.getvalue()


def _module(cfg_path: pathlib.Path) -> str:
    cfg = json.loads(cfg_path.read_text(encoding="utf-8"))
    raw = str(cfg.get("id", cfg_path.stem)).replace(" ", "_")
    return module_safe_name(camel_to_snake(raw))


def _gen(src: pathlib.Path, out: pathlib.Path, *extra: str) -> Tuple[int, str]:
    return _run(
        [
            "gt",
            str(src),
            "-t",
            "pythonic-class",
            "--with-api",
            "--with-models",
            "-o",
            str(out),
            "--plain",
            *extra,
        ]
    )


def _strip_banner(text: str) -> str:
    return "\n".join(
        ln
        for ln in text.splitlines()
        if not ln.startswith("# Generated by")
        and "xstate-statemachine " not in ln
    )


def _import_fresh(out: pathlib.Path, name: str) -> Any:
    # 📝 charts sharing an `id` generate the same module names; evict every
    #    generated module so `<x>_api` never binds a stale `<x>_models`
    for mod in [m for m in sys.modules if m.endswith(("_api", "_models"))]:
        sys.modules.pop(mod, None)
    importlib.invalidate_caches()
    if str(out) not in sys.path:
        sys.path.insert(0, str(out))
    try:
        return importlib.import_module(name)
    finally:
        sys.path.remove(str(out))


# -----------------------------------------------------------------------------
# 1. the whole corpus
# -----------------------------------------------------------------------------
def test_whole_corpus_generates_parses_imports_mounts(
    tmp_path: pathlib.Path,
) -> None:
    """Every corpus chart (~2.5 min in-process) when ``XSM_FULL_CORPUS=1``
    (the Linux 3.14 CI cell and the battle gates); a deterministic
    12-chart sample -- including the id-colliding and the refused ones --
    on every other run (review M1: the full pass added 2.5 min to every
    cell of the matrix)."""
    import os

    from fastapi import FastAPI

    charts = sorted(CORPUS.glob("*.json"))
    if os.environ.get("XSM_FULL_CORPUS") != "1":
        must = {"emailProcessing.json", "debt.json", "APA_Logic.json"}
        picked = [c for c in charts if c.name in must]
        picked += [c for c in charts if c.name not in must][::9]
        charts = sorted(set(picked))[:12]
        # keep one id collision in the sample
        debt = [
            c
            for c in sorted(CORPUS.glob("*.json"))
            if "debt" in c.name.lower()
        ]
        charts = sorted(set(charts) | set(debt[:2]))
    refused: Dict[str, str] = {}
    by_module: Dict[str, List[str]] = {}
    for src in charts:
        out = tmp_path / src.stem
        out.mkdir()
        code, text = _gen(src, out, "-f")
        if code != 0:
            refused[src.name] = (
                text.strip().splitlines()[-1][:120] if text else ""
            )
            continue
        api = list(out.glob("*_api.py"))
        assert len(api) == 1, (src.name, sorted(p.name for p in out.iterdir()))
        by_module.setdefault(api[0].stem, []).append(src.name)
        for f in list(out.glob("*_api.py")) + list(out.glob("*_models.py")):
            ast.parse(f.read_text("utf-8"), filename=str(f))
        mod = _import_fresh(out, api[0].stem)
        app = FastAPI()
        app.include_router(mod.router)
        doc = app.openapi()
        cfg = json.loads(src.read_text("utf-8"))
        from src.xstate_statemachine.contrib.starlette._http import (
            declared_events,
        )
        from src.xstate_statemachine import create_machine, stub_logic

        machine = create_machine(cfg, logic=stub_logic(cfg))
        want = len(declared_events(machine))
        got = sum(1 for p in doc["paths"] if "/events/" in p)
        assert got == want, (src.name, got, want)
    # the deliberate refusals are the known ones, each with a reason
    assert set(refused) <= {"emailProcessing.json"}, refused
    for name, reason in refused.items():
        assert reason, name
    # charts whose ids collide produce the same filename
    collisions = {m: v for m, v in by_module.items() if len(v) > 1}
    assert collisions, "the sample must contain an id collision"


def test_colliding_module_names_are_reported_by_check(
    tmp_path: pathlib.Path,
) -> None:
    """Two corpus charts with the same `id` write the same `_api.py`; the
    second overwrote the first silently. `--check` after the second must
    say the file on disk is NOT the first chart's output."""
    a = CORPUS / "debt.json"
    others = [
        p
        for p in sorted(CORPUS.glob("*.json"))
        if p != a
        and json.loads(p.read_text("utf-8")).get("id")
        == json.loads(a.read_text("utf-8")).get("id")
    ]
    assert others, "no second chart with the same id"
    b = others[0]
    assert _gen(a, tmp_path, "-f")[0] == 0
    assert _gen(b, tmp_path, "-f")[0] == 0
    code, text = _gen(a, tmp_path, "--check")
    assert code == 1, text  # a's output was overwritten by b's
    assert "out of date" in text


# -----------------------------------------------------------------------------
# 2. byte-stable regeneration
# -----------------------------------------------------------------------------
def test_regeneration_is_byte_stable_and_check_detects_drift(
    tmp_path: pathlib.Path,
) -> None:
    src = tmp_path / "pay.json"
    cfg = json.loads((CORPUS / "AdvancePayment.json").read_text("utf-8"))
    src.write_text(json.dumps(cfg), encoding="utf-8")
    assert _gen(src, tmp_path, "-f")[0] == 0
    first = {
        f.name: _strip_banner(f.read_text("utf-8"))
        for f in tmp_path.glob("*.py")
    }
    time.sleep(1.1)  # a banner timestamp, if any, moves
    assert _gen(src, tmp_path, "-f")[0] == 0
    second = {
        f.name: _strip_banner(f.read_text("utf-8"))
        for f in tmp_path.glob("*.py")
    }
    assert first == second
    code, text = _gen(src, tmp_path, "--check")
    assert code == 0 and "up to date" in text
    cfg["states"]["challenge"]["on"]["NUDGE"] = {"target": "challenge"}
    src.write_text(json.dumps(cfg), encoding="utf-8")
    code, text = _gen(src, tmp_path, "--check")
    assert code == 1 and "out of date" in text
    code, text = _gen(src, tmp_path, "--diff")
    assert code == 1 and "/events/NUDGE" in text


# -----------------------------------------------------------------------------
# 3. the generated router keeps the registry's rules
# -----------------------------------------------------------------------------
def test_generated_router_denial_saves_nothing_and_stub_raises(
    tmp_path: pathlib.Path,
) -> None:
    from fastapi import FastAPI
    from fastapi.testclient import TestClient

    # 📝 the generated module imports the INSTALLED package name; the
    #    registry / exception classes must be the same objects (two copies
    #    of the package would make `instrument_app`'s handler miss)
    from xstate_statemachine import create_machine, stub_logic
    from xstate_statemachine.contrib.fastapi import instrument_app

    src = CORPUS / "AdvancePayment.json"
    assert _gen(src, tmp_path, "-f")[0] == 0
    api = _import_fresh(tmp_path, _module(src) + "_api")
    cfg = json.loads(src.read_text("utf-8"))
    machine = create_machine(cfg, logic=stub_logic(cfg))
    # X0.1: the stub refuses until implemented
    with pytest.raises(NotImplementedError):
        api.authorize(None, name="x", key="k", event=None)

    def authorize(conn: Any, *, name: str, key: str, event: Any) -> bool:
        return event != "RETRY"

    api.register(machine, authorize=authorize)
    app = FastAPI()
    app.include_router(api.router)
    instrument_app(app, api.registry)
    base = f"/{api.MACHINE_NAME}/k"
    # 📝 the denial is RAISED and mapped by instrument_app's handler; the
    #    TestClient re-raises handled server exceptions unless told not to
    with TestClient(app, raise_server_exceptions=False) as c:
        assert c.get(base).status_code == 200
        r = c.post(f"{base}/events/SUBMIT", json={})
        assert r.status_code == 200 and r.json()["state"] == "challenge"
        skey = api.registry.store_key(api.MACHINE_NAME, "k")
        v1 = api.registry.store.load(skey).version
        r = c.post(f"{base}/events/RETRY", json={})
        assert r.status_code == 403
        # 🔥 a refused request must not save: the version is unchanged
        assert api.registry.store.load(skey).version == v1
        assert c.post(f"{base}/events/NOPE", json={}).status_code == 404
        r = c.post(
            f"{base}/events/SUBMIT", json={}, headers={"Idempotency-Key": "x"}
        )
        assert r.status_code == 501


# -----------------------------------------------------------------------------
# 4. odd names
# -----------------------------------------------------------------------------
def test_odd_event_names_slug_uniquely_or_are_refused(
    tmp_path: pathlib.Path,
) -> None:
    from fastapi import FastAPI

    cfg = {
        "id": "odd",
        "initial": "a",
        "states": {
            "a": {
                "on": {
                    "with space": "a",
                    "colon:sep": "a",
                    "bang!": "a",
                    "slash/sep": "a",
                    "éclair": "a",
                    "ORDER.PAID": "a",
                    "ORDER_PAID": "a",
                }
            }
        },
    }
    src = tmp_path / "odd.json"
    src.write_text(json.dumps(cfg), encoding="utf-8")
    code, text = _gen(src, tmp_path, "-f")
    assert code == 0, text
    mod = _import_fresh(tmp_path, "odd_api")
    app = FastAPI()
    app.include_router(mod.router)
    doc = app.openapi()
    routes = [p for p in doc["paths"] if "/events/" in p]
    assert len(routes) == 7, routes
    ops = [
        op["operationId"] for p in routes for op in doc["paths"][p].values()
    ]
    assert len(ops) == len(set(ops)), ops
    assert all(o.isascii() for o in ops), ops
    # two events that slug to the SAME identifier keep DISTINCT routes
    # (the raw slugs differ) and unique operationIds -- never merged
    cfg["states"]["a"]["on"] = {"pay now": "a", "pay-now": "a"}
    src.write_text(json.dumps(cfg), encoding="utf-8")
    code, text = _gen(src, tmp_path, "-f")
    assert code == 0, text
    mod = _import_fresh(tmp_path, "odd_api")
    app = FastAPI()
    app.include_router(mod.router)
    doc = app.openapi()
    routes = sorted(
        p for p in doc["paths"] if "/events/" in p and "{event}" not in p
    )
    assert len(routes) == 2, routes
    ops = [
        op["operationId"] for p in routes for op in doc["paths"][p].values()
    ]
    assert len(set(ops)) == 2, ops


# -----------------------------------------------------------------------------
# 5. Windows paths
# -----------------------------------------------------------------------------
def test_output_dir_with_spaces_and_unicode(tmp_path: pathlib.Path) -> None:
    out = tmp_path / "my project ✓"
    out.mkdir()
    src = CORPUS / "AdvancePayment.json"
    code, text = _gen(src, out, "-f")
    assert code == 0, text
    files = sorted(p.name for p in out.glob("*.py"))
    assert any(f.endswith("_api.py") for f in files), files
    for f in out.glob("*.py"):
        txt = f.read_text("utf-8")
        assert "Ã" not in txt and "â€" not in txt  # mojibake
    assert "Ã" not in text and "â€" not in text


# -----------------------------------------------------------------------------
# 6. performance
# -----------------------------------------------------------------------------
def test_fifty_event_chart_generates_in_bounded_time(
    tmp_path: pathlib.Path,
) -> None:
    cfg = {
        "id": "wide",
        "initial": "a",
        "states": {"a": {"on": {f"E{n}": "a" for n in range(50)}}},
    }
    src = tmp_path / "wide.json"
    src.write_text(json.dumps(cfg), encoding="utf-8")
    t0 = time.perf_counter()
    code, text = _gen(src, tmp_path, "-f")
    took = time.perf_counter() - t0
    assert code == 0, text
    assert took < 20.0, took
    t0 = time.perf_counter()
    code, text = _gen(src, tmp_path, "--check")
    assert code == 0 and time.perf_counter() - t0 < 20.0
