# Generated by Django 6.1.1 (the test project's shop app).

import xstate_statemachine.contrib.django.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Counter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "statechart",
                    xstate_statemachine.contrib.django.fields.StatechartField(),
                ),
                (
                    "statechart_state",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=512,
                        null=True,
                    ),
                ),
                (
                    "statechart_state_ids",
                    models.JSONField(blank=True, editable=False, null=True),
                ),
                (
                    "statechart_version",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                (
                    "statechart_machine_version",
                    models.CharField(
                        blank=True, editable=False, max_length=255, null=True
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "statechart",
                    xstate_statemachine.contrib.django.fields.StatechartField(),
                ),
                (
                    "statechart_state",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=512,
                        null=True,
                    ),
                ),
                (
                    "statechart_state_ids",
                    models.JSONField(blank=True, editable=False, null=True),
                ),
                (
                    "statechart_version",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                (
                    "statechart_machine_version",
                    models.CharField(
                        blank=True, editable=False, max_length=255, null=True
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
