# src/xstate_statemachine/cli/strategies/_shared.py
"""Shared helpers used across all code generation strategies."""

import keyword

from typing import Dict, List, Optional, Set

from ...pythonic import _snake_to_camel
from ..naming import docstring_safe
from ..utils import camel_to_snake


def pascal_case_name(snake_name: str) -> str:
    """Convert snake_case to PascalCase for class names."""
    return "".join(word.capitalize() for word in snake_name.split("_"))


def generate_module_header(title: str) -> str:
    """Generate the module docstring matching spec format."""
    return f'"""{title} state machine ' f'-- generated by xsm CLI."""\n'


def generate_section_header(title: str) -> str:
    """Generate a section separator comment block."""
    return "\n".join(
        [
            "# --------------------------------------------------"
            "---------------------",
            f"# {title}",
            "# --------------------------------------------------"
            "---------------------",
            "",
        ]
    )


def generate_logger_setup(log: bool) -> str:
    """Generate logger variable line.

    The import statement is handled by generate_imports.
    """
    if not log:
        return ""
    return "\n".join(
        [
            "logger = logging.getLogger(__name__)",
            "",
        ]
    )


def generate_action_docstring(original_name: str, component_type: str) -> str:
    """Generate a rich docstring with Args section.

    Args:
        original_name: The original camelCase name from JSON.
        component_type: One of 'action', 'guard', 'service'.

    Returns:
        A multi-line docstring string (without outer quotes).
    """
    verbs = {
        "action": "Execute",
        "guard": "Evaluate",
        "service": "Run",
    }
    verb = verbs.get(component_type, "Execute")
    # 🛡️ SECURITY: a name containing `"""` would close this docstring
    #    early and turn the remainder into executable code.
    safe_name = docstring_safe(original_name)
    lines = [f"{verb} the ``{safe_name}`` {component_type}."]
    lines.append("")
    lines.append("Args:")
    if component_type == "guard":
        lines.append("    context: Current machine context dictionary.")
        lines.append("    event: The event being evaluated.")
    else:
        lines.append("    interpreter: The running interpreter instance.")
        lines.append("    context: Mutable machine context dictionary.")
        lines.append(
            f"    event: The event that triggered this " f"{component_type}."
        )
        if component_type == "action":
            lines.append(
                "    action_def: Metadata about the action " "being executed."
            )
    return "\n".join(lines)


def generate_error_handling(
    original_name: str,
    component_type: str,
    body_lines: List[str],
    indent: str,
    log: bool = True,
) -> str:
    """Wrap body lines in try/except with logger.exception.

    Args:
        original_name: The original camelCase name from JSON.
        component_type: One of 'action', 'guard', 'service'.
        body_lines: The lines of code to wrap.
        indent: The indentation string (e.g. '    ').
        log: Whether logging is enabled (controls logger.exception usage).

    Returns:
        The wrapped code as a string.
    """
    # When logging is disabled, try/except that just re-raises is
    # pointless dead code — emit the body lines directly instead.
    if not log:
        result: List[str] = []
        has_statement = False
        for line in body_lines:
            stripped = line.lstrip()
            if stripped:
                result.append(f"{indent}{stripped}")
                if not stripped.startswith("#"):
                    has_statement = True
            else:
                result.append("")
        if not has_statement:
            result.append(f"{indent}pass")
        return "\n".join(result)

    lines = [f"{indent}try:"]
    # Track whether the try body contains any executable statements
    has_statement = False
    for line in body_lines:
        stripped = line.lstrip()
        if stripped:
            lines.append(f"{indent}    {stripped}")
            # Comments are not executable statements
            if not stripped.startswith("#"):
                has_statement = True
        else:
            lines.append("")
    # Ensure the try block has at least one executable statement
    if not has_statement:
        lines.append(f"{indent}    pass")
    lines.append(f"{indent}except Exception:")
    safe_name = escape_for_string(original_name)
    lines.append(
        f"{indent}    logger.exception("
        f'"{component_type.capitalize()} '
        f"'{safe_name}' failed\")"
    )
    lines.append(f"{indent}    raise")
    return "\n".join(lines)


def generate_imports(
    is_async: bool,
    services: Set[str],
    template_type: str,
    log: bool = True,
    actions: Optional[Set[str]] = None,
    guards: Optional[Set[str]] = None,
) -> str:
    """Generate import statements for the template type.

    Args:
        is_async: Whether async mode is enabled.
        services: Set of service names (may affect imports).
        template_type: The template identifier string.
        log: Whether logging is enabled (adds import logging).

    Returns:
        Import block as a string.
    """
    lines: List[str] = []

    if template_type.startswith("pythonic"):
        if is_async:
            lines.append("import asyncio")
        if log:
            lines.append("import logging")
        lines.append("from typing import Any, Dict, Optional, Union")
        lines.append("")
        interpreter = "Interpreter" if is_async else "SyncInterpreter"
        xsm_imports = [interpreter]
        # Both Interpreter and SyncInterpreter are needed for
        # Union[Interpreter, SyncInterpreter] type hints in generated code.
        other = "SyncInterpreter" if is_async else "Interpreter"
        if other not in xsm_imports:
            xsm_imports.append(other)
        if "class" in template_type:
            xsm_imports.extend(
                [
                    "State",
                    "StateMachine",
                    "action",
                    "guard",
                ]
            )
            if services:
                xsm_imports.append("service")
        elif "builder" in template_type:
            xsm_imports.extend(
                [
                    "MachineBuilder",
                    "action",
                    "guard",
                ]
            )
            if services:
                xsm_imports.append("service")
        elif "functional" in template_type:
            xsm_imports.extend(
                [
                    "State",
                    "action",
                    "build_machine",
                    "guard",
                ]
            )
            if services:
                xsm_imports.append("service")
        xsm_imports.sort()
        imports_str = ",\n    ".join(xsm_imports)
        lines.append(
            f"from xstate_statemachine import (\n" f"    {imports_str},\n)"
        )
    else:
        # JSON-style imports
        if is_async:
            lines.append("import asyncio")
        if log:
            lines.append("import logging")
        if services and not is_async:
            lines.append("import time")
        lines.append("from typing import Any, Dict, Union")
        lines.append("")
        # 🏷️ Config names that do not round-trip through snake_case ->
        #    camelCase (Stately `inline:...`, dotted/dashed names) are bound
        #    with `@action("<original>")`, so the decorators are imported
        #    only when at least one such name exists -- keeps ordinary
        #    generated files free of unused imports.
        markers = sorted(
            kind
            for kind, names in (
                ("action", actions or set()),
                ("guard", guards or set()),
                ("service", services),
            )
            if any(needs_explicit_name(n) for n in names)
        )
        extra = "".join(f", {m}" for m in markers)
        lines.append(
            "from xstate_statemachine import "
            "Interpreter, SyncInterpreter, Event, "
            f"ActionDefinition{extra}"
        )

    lines.append("")
    return "\n".join(lines)


def snake_case_name(camel_name: str) -> str:
    """Convert camelCase to snake_case."""
    return camel_to_snake(camel_name)


def logic_bindings(
    actions: Set[str], guards: Set[str], services: Set[str]
) -> Dict[str, str]:
    """Map every logic name to a unique Python identifier for one module.

    🏛️ Architecture decision: the identifier for a config name is decided
    ONCE here and read everywhere -- the `def`, the decorator, and every
    reference (`builder.action(name, fn)`, `actions=[fn, ...]`). Each site
    used to call `snake_case_name` independently, which agreed by luck and
    could not de-duplicate: `fetch-data` and `fetch.data` both became
    `fetch_data`, so the second `def` silently replaced the first and one
    config name had no implementation at runtime. Allocation is over the
    sorted union of all three kinds, in one namespace, because they share
    one module. Deterministic: same input, same identifiers.
    """
    taken: Set[str] = set()
    out: Dict[str, str] = {}
    for name in sorted(actions | guards | services):
        base = snake_case_name(name)
        if keyword.iskeyword(base):
            base = f"{base}_"
        candidate, suffix = base, 2
        while candidate in taken:
            candidate = f"{base}_{suffix}"
            suffix += 1
        taken.add(candidate)
        out[name] = candidate
    return out


def needs_explicit_name(original: str, fn_name: Optional[str] = None) -> bool:
    """True when *original* cannot be recovered from *fn_name*.

    The bare decorator registers `_snake_to_camel(fn_name)`; if that is
    not the config name, the explicit `@action("<original>")` form is
    required. *fn_name* defaults to the plain snake_case form.
    """
    if fn_name is None:
        fn_name = snake_case_name(original)
        if keyword.iskeyword(fn_name):
            fn_name = f"{fn_name}_"
    return _snake_to_camel(fn_name) != original


def decorator_for(component_type: str, original: str, fn_name: str) -> str:
    """The ``@action`` / ``@guard`` / ``@service`` line for one stub.

    🏛️ Architecture decision: the bare decorator registers a method under
    ``_snake_to_camel(fn.__name__)``. For a config name that is itself a
    plain camelCase identifier that round-trips exactly, so ``@action`` on
    ``def fetch_data`` binds ``fetchData`` -- the generated code stays as
    clean as hand-written. But Stately exports anonymous actions as
    ``inline:machine.state#entry[0]``, and names with dots, dashes, digits
    or leading capitals do not survive snake_case -> camelCase either.
    Emitting the bare decorator for those bound the method under a name
    the config never uses, and every such machine raised
    ``ImplementationMissingError`` at ``start()`` -- 26 of the 104
    real-world corpus machines. When the round-trip is lossy, emit the
    explicit-name form the decorators already accept.
    """
    if not needs_explicit_name(original, fn_name):
        return f"@{component_type}"
    return f'@{component_type}("{escape_for_string(original)}")'


def safe_identifier(name: str) -> str:
    """Ensure *name* is a valid Python identifier.

    If *name* is a Python keyword (``class``, ``return``, …), an
    underscore suffix is appended (``class_``).  Non-identifier
    characters are replaced with underscores.

    Args:
        name: The raw name from JSON config.

    Returns:
        A string safe to use as a Python variable name.
    """
    # Replace characters that aren't valid in identifiers
    safe = "".join(c if c.isalnum() or c == "_" else "_" for c in name)
    # Ensure it doesn't start with a digit
    if safe and safe[0].isdigit():
        safe = f"s_{safe}"
    # Avoid Python keywords
    if keyword.iskeyword(safe):
        safe = f"{safe}_"
    return safe


def escape_for_string(name: str) -> str:
    """Escape a raw name so it can be safely embedded in a Python string literal.

    Replaces backslashes first, then double-quotes and single-quotes,
    producing a value safe inside ``"..."`` *or* ``'...'`` delimiters.

    Args:
        name: The raw name from JSON config.

    Returns:
        An escaped string safe for embedding in Python string literals.
    """
    return name.replace("\\", "\\\\").replace('"', '\\"').replace("'", "\\'")


# ---------------------------------------------------------------------------
# Recursive state/transition collection for nested/hierarchical machines
# ---------------------------------------------------------------------------
