# src/xstate_statemachine/cli/strategies/_shared.py
"""Shared helpers used across all code generation strategies."""

from typing import List, Set

from ..utils import camel_to_snake


def pascal_case_name(snake_name: str) -> str:
    """Convert snake_case to PascalCase for class names."""
    return "".join(word.capitalize() for word in snake_name.split("_"))


def generate_module_header(title: str, json_filename: str) -> str:
    """Generate the module docstring matching spec format."""
    return f'"""{title} state machine ' f'-- generated by xsm CLI."""\n'


def generate_section_header(title: str) -> str:
    """Generate a section separator comment block."""
    return "\n".join(
        [
            "# --------------------------------------------------"
            "---------------------",
            f"# {title}",
            "# --------------------------------------------------"
            "---------------------",
            "",
        ]
    )


def generate_logger_setup(log: bool) -> str:
    """Generate logger variable line.

    The import statement is handled by generate_imports.
    """
    if not log:
        return ""
    return "\n".join(
        [
            "logger = logging.getLogger(__name__)",
            "",
        ]
    )


def generate_action_docstring(original_name: str, component_type: str) -> str:
    """Generate a rich docstring with Args section.

    Args:
        original_name: The original camelCase name from JSON.
        component_type: One of 'action', 'guard', 'service'.

    Returns:
        A multi-line docstring string (without outer quotes).
    """
    verbs = {
        "action": "Execute",
        "guard": "Evaluate",
        "service": "Run",
    }
    verb = verbs.get(component_type, "Execute")
    lines = [f"{verb} the ``{original_name}`` {component_type}."]
    lines.append("")
    lines.append("Args:")
    if component_type == "guard":
        lines.append("    context: Current machine context dictionary.")
        lines.append("    event: The event being evaluated.")
    else:
        lines.append("    interpreter: The running interpreter instance.")
        lines.append("    context: Mutable machine context dictionary.")
        lines.append(
            f"    event: The event that triggered this " f"{component_type}."
        )
        if component_type == "action":
            lines.append(
                "    action_def: Metadata about the action " "being executed."
            )
    return "\n".join(lines)


def generate_error_handling(
    original_name: str,
    component_type: str,
    body_lines: List[str],
    indent: str,
) -> str:
    """Wrap body lines in try/except with logger.exception.

    Args:
        original_name: The original camelCase name from JSON.
        component_type: One of 'action', 'guard', 'service'.
        body_lines: The lines of code to wrap.
        indent: The indentation string (e.g. '    ').

    Returns:
        The wrapped code as a string.
    """
    lines = [f"{indent}try:"]
    for line in body_lines:
        lines.append(f"{indent}    {line.lstrip()}")
    lines.append(f"{indent}except Exception:")
    lines.append(
        f"{indent}    logger.exception("
        f'"{component_type.capitalize()} '
        f"'{original_name}' failed\")"
    )
    lines.append(f"{indent}    raise")
    return "\n".join(lines)


def generate_imports(
    is_async: bool,
    services: Set[str],
    template_type: str,
    log: bool = True,
) -> str:
    """Generate import statements for the template type.

    Args:
        is_async: Whether async mode is enabled.
        services: Set of service names (may affect imports).
        template_type: The template identifier string.
        log: Whether logging is enabled (adds import logging).

    Returns:
        Import block as a string.
    """
    lines: List[str] = []

    if template_type.startswith("pythonic"):
        if is_async:
            lines.append("import asyncio")
        if log:
            lines.append("import logging")
        lines.append("from typing import Any, Dict, Optional, Union")
        lines.append("")
        interpreter = "Interpreter" if is_async else "SyncInterpreter"
        xsm_imports = [interpreter]
        if "class" in template_type:
            xsm_imports.extend(
                [
                    "State",
                    "StateMachine",
                    "action",
                    "guard",
                    "service",
                    "transition",
                ]
            )
        elif "builder" in template_type:
            xsm_imports.extend(
                [
                    "MachineBuilder",
                    "action",
                    "guard",
                    "service",
                ]
            )
        elif "functional" in template_type:
            xsm_imports.extend(
                [
                    "State",
                    "action",
                    "build_machine",
                    "guard",
                    "service",
                ]
            )
        xsm_imports.sort()
        imports_str = ",\n    ".join(xsm_imports)
        lines.append(
            f"from xstate_statemachine import (\n" f"    {imports_str},\n)"
        )
    else:
        # JSON-style imports
        if is_async:
            lines.append("import asyncio")
        if log:
            lines.append("import logging")
        if services and not is_async:
            lines.append("import time")
        lines.append("from typing import Any, Dict, Union")
        lines.append("")
        lines.append(
            "from xstate_statemachine import "
            "Interpreter, SyncInterpreter, Event, "
            "ActionDefinition"
        )

    lines.append("")
    return "\n".join(lines)


def snake_case_name(camel_name: str) -> str:
    """Convert camelCase to snake_case."""
    return camel_to_snake(camel_name)
