# src/xstate_statemachine/cli/strategies/fastapi_router.py
# -----------------------------------------------------------------------------
# 🛣️ `fastapi-router` template -- `<machine>_api.py`, a router you own
# -----------------------------------------------------------------------------
# `StatechartRouter` builds a chart's API at runtime; this template writes
# the same surface out as ordinary, editable FastAPI code:
#   * `registry` -- a module-level `StatechartRegistry` (MemoryStore until
#     you swap in your store) and `register(machine)` to add the chart;
#   * `authorize(conn, *, name, key, event)` -- a stub that RAISES
#     (X0.1: closed by default -- nothing is served until you decide who
#     may do what);
#   * `GET /{id}` -- the current state (never the context);
#   * one `POST /{id}/events/<EVENT>` per declared event, typed by the
#     matching `EventModel` when `--with-models` is on (else a permissive
#     JSON object), through `Depends(get_interpreter(...))` and answered
#     with `ReceiptResponse`;
#   * `POST /{id}/events/{event}` -- an unknown event is a 404 problem.
#
# 📝 No `from __future__ import annotations` in the OUTPUT: FastAPI reads
#    handler annotations at `def` time.
# -----------------------------------------------------------------------------
"""The `fastapi-router` code-generation strategy."""

from __future__ import annotations

from typing import List

from ._shared import generate_module_header, generate_section_header
from ._web import EventSpec, collect_events, machine_prose
from .base import BaseStrategy, GenerationContext

#: The companion whose output the router imports when both are emitted.
MODELS_TEMPLATE = "pydantic-models"


def models_module(ctx: GenerationContext) -> str:
    return f"{ctx.machine_name}_models"


def _handler(spec: EventSpec, typed: bool) -> List[str]:
    body_ann = (
        f"Optional[{spec.class_name}]" if typed else "Optional[Dict[str, Any]]"
    )
    doc = spec.doc or f"Send {spec.type}."
    return [
        "@router.post(",
        f"    {('/{id}/events/' + spec.path)!r},",
        f"    operation_id=f{'{MACHINE_NAME}_' + spec.ident!r},",
        f"    summary={('Send ' + spec.type)!r},",
        "    response_model=None,",
        "    responses=SEND_RESPONSES,",
        ")",
        f"async def send_{spec.ident}(",
        "    request: Request,",
        "    instance_id: str = INSTANCE_ID,",
        f"    body: {body_ann} = Body(None),",
        '    interp: Any = get_interpreter(registry, MACHINE_NAME, key="id"),',
        ") -> Response:",
        f'    """{doc}"""',
        f"    return await _send(request, interp, {spec.type!r}, _payload(body))",
        "",
        "",
    ]


class FastAPIRouterStrategy(BaseStrategy):
    """Generates an editable FastAPI router for one machine."""

    @property
    def name(self) -> str:
        return "fastapi-router"

    def generate_runner(self, ctx: GenerationContext) -> str:
        return ""

    def generate_logic(self, ctx: GenerationContext) -> str:
        config = ctx.configs[0]
        events = collect_events(config)
        typed = MODELS_TEMPLATE in ctx.companions
        prose = machine_prose(config)
        name = ctx.machine_name
        p: List[str] = [
            generate_module_header(f"FastAPI router for the {name}"),
            "# Generated by `xsm generate-template --template fastapi-router`.",
            "# Imports only the [fastapi] extra:",
            '#     pip install "xstate-statemachine[fastapi]"',
            "# A starting point you own: either edit it (and stop regenerating /",
            "# drop it from `--check`), or keep custom routes in your own module",
            "# and regenerate this one freely. Wire it with",
            "#     app = FastAPI()",
            f"#     register(build_{name}_machine())  # your create_machine(...)",
            "#     app.include_router(router)",
            "#     instrument_app(app, registry)  # probes, lifespan, problem+json",
            "# `xsm gt ... --check` in CI reports drift when the chart changes.",
            "",
            "from typing import Any, Dict, Optional",
            "",
            "from fastapi import APIRouter, Body, Path, Request",
            "from fastapi.exceptions import RequestValidationError",
            "from fastapi.routing import APIRoute",
            "from starlette.requests import HTTPConnection",
            "from starlette.responses import JSONResponse, Response",
            "",
            "from xstate_statemachine.contrib.fastapi import (",
            "    ReceiptResponse,",
            "    StatechartRegistry,",
            "    get_interpreter,",
            "    problem,",
            "    problem_for_exception,",
            ")",
            "from xstate_statemachine.persistence import MemoryStore",
        ]
        if typed and events:
            p.append(f"from {models_module(ctx)} import (")
            p += [f"    {s.class_name}," for s in events]
            p.append(")")
        p += [
            "",
            f"MACHINE_NAME = {name!r}",
            "",
            "",
            generate_section_header("Authorization (X0.1: closed by default)"),
            "def authorize(",
            "    conn: HTTPConnection, *, name: str, key: str, event: Optional[str]",
            ") -> bool:",
            '    """Decide whether *conn* may read (``event=None``) or send *event*',
            '    to instance *key*. Return True to admit, False for a 403."""',
            "    # 🔐 X0.1 -- closed by default. A generated API must not serve",
            "    #    anyone until you decide who may read and drive which",
            "    #    instance, so this stub RAISES instead of admitting: an",
            "    #    unfinished router fails loudly (500) rather than shipping",
            "    #    wide open. Replace the body with your check, e.g.",
            "    #        return conn.user.is_authenticated and owns(conn.user, key)",
            "    #    For a local demo ONLY, pass `authorize=allow_all` to",
            "    #    `register()` -- it logs a warning the first time it is used.",
            "    raise NotImplementedError(",
            "        'authorize() is a generated stub: implement it (X0.1)'",
            "    )",
            "",
            "",
            generate_section_header("Registry"),
            "# 🧩 MemoryStore keeps instances in this process only -- swap in",
            "#    your StateStore (SQLite, Redis, Postgres ...) for production.",
            "registry = StatechartRegistry(MemoryStore())",
            "",
            "",
            "def register(machine: Any, *, authorize: Any = authorize, **kwargs: Any) -> None:",
            f'    """Register *machine* (built from the {name} chart) with `registry`."""',
            "    registry.register(MACHINE_NAME, machine, authorize=authorize, **kwargs)",
            "",
            "",
            generate_section_header("Routing plumbing"),
            "class _ProblemRoute(APIRoute):",
            '    """Validation failures as problem+json listing only field location',
            '    and error type -- never the rejected input (X0.7)."""',
            "",
            "    def get_route_handler(self) -> Any:",
            "        handler = super().get_route_handler()",
            "",
            "        async def route(request: Request) -> Response:",
            "            try:",
            "                return await handler(request)",
            "            except RequestValidationError as exc:",
            "                errors = [",
            '                    {"loc": [str(x) for x in e.get("loc", ())],',
            '                     "type": str(e.get("type", ""))}',
            "                    for e in exc.errors()",
            "                ]",
            '                return problem(422, "Request validation failed", errors=errors)',
            "",
            "        return route",
            "",
            "",
            f"router = APIRouter(prefix={('/' + name)!r}, tags=[{name!r}], route_class=_ProblemRoute)",
            'INSTANCE_ID = Path(..., alias="id")',
            "SEND_RESPONSES: Dict[Any, Any] = {",
            '    200: {"description": "Receipt: state after the event"},',
            '    202: {"description": "Deferred"},',
            '    403: {"description": "Forbidden (authorize)"},',
            '    404: {"description": "Unknown event"},',
            '    409: {"description": "Guard denied / write conflict"},',
            '    422: {"description": "Invalid payload"},',
            "}",
            "",
            "",
            "def _payload(body: Any) -> Dict[str, Any]:",
            "    if body is None:",
            "        return {}",
            "    if isinstance(body, dict):",
            "        return dict(body)",
            '    return body.model_dump(mode="python", by_alias=True, exclude={"type"})',
            "",
            "",
            "async def _send(",
            "    request: Request, interp: Any, event: str, payload: Dict[str, Any]",
            ") -> Response:",
            '    key = str(request.path_params["id"])',
            "    try:",
            "        await registry.authorize(request, MACHINE_NAME, key, event)",
            "        receipt = await interp.send(event, wait=True, **payload)",
            "    except Exception as exc:  # noqa: BLE001 -- mapped, never leaked",
            "        return problem_for_exception(exc)",
            "    return ReceiptResponse(interp, receipt)",
            "",
            "",
            generate_section_header("Routes"),
            '@router.get("/{id}", operation_id=f"{MACHINE_NAME}_get", response_model=None)',
            "async def get_state(request: Request, instance_id: str = INSTANCE_ID) -> Response:",
            f'    """Current state of a {name} instance{(": " + prose) if prose else ""}"""',
            "    try:",
            "        await registry.authorize(request, MACHINE_NAME, instance_id, None)",
            "        body = await registry.peek(MACHINE_NAME, instance_id)",
            "    except Exception as exc:  # noqa: BLE001 -- mapped, never leaked",
            "        return problem_for_exception(exc)",
            "    return JSONResponse(body)",
            "",
            "",
        ]
        for spec in events:
            p += _handler(spec, typed)
        p += [
            "# 📝 Declared LAST: the literal routes above win; anything else is",
            "#    an event this chart does not declare.",
            '@router.post("/{id}/events/{event}", include_in_schema=False)',
            "async def unknown_event(event: str) -> Response:",
            '    return problem(404, "Unknown event")',
            "",
            "",
            f"DECLARED_EVENTS = {[s.type for s in events]!r}",
            "",
        ]
        return "\n".join(p)
