# src/xstate_statemachine/cli/strategies/pytest_scaffold.py
# -----------------------------------------------------------------------------
# 🧪 `pytest` template -- a test module per machine, from a recorded trace
# -----------------------------------------------------------------------------
# What it generates, per machine:
#   * a fixture that builds the machine with STUB logic (every action records
#     its name, every guard returns True, every service returns None) on a
#     `SimulatedClock` -- the tests are about the CHART, not the user's code;
#   * `test_initial_state`;
#   * one `test_step_NN_<event>` per recorded step asserting the exact
#     configuration after it (and that the expected actions ran);
#   * a timer test for each recorded clock advance;
#   * a guard-denied test per guard (guards forced False → configuration
#     unchanged and `Receipt.denied` on the first guarded event);
#   * `test_every_declared_event_is_known` under `strict`;
#   * a snapshot round-trip test.
# The trace is ground truth recorded from the real engine at generation
# time (see `_trace.record`), so a failing generated test means the chart
# or the library changed -- never a generator guess.
# -----------------------------------------------------------------------------
"""The `pytest` code-generation strategy."""

from __future__ import annotations

import json
from typing import Any, Dict, List

from ..utils import camel_to_snake
from ._shared import (
    generate_module_header,
    generate_section_header,
    safe_identifier,
)
from ._trace import Trace, record
from .base import BaseStrategy, GenerationContext


def _py(obj: Any) -> str:
    """A Python literal for a JSON-ish value (lists / strings / None)."""
    return repr(obj)


class PytestScaffoldStrategy(BaseStrategy):
    """Generates a pytest module that pins a machine's observed behaviour."""

    @property
    def name(self) -> str:
        return "pytest"

    # The scaffold IS the "logic" artefact; there is no separate runner.
    def generate_runner(self, ctx: GenerationContext) -> str:
        return ""

    def generate_logic(self, ctx: GenerationContext) -> str:
        config = ctx.configs[0]
        trace = record(config)
        mod = camel_to_snake(safe_identifier(ctx.machine_name))
        parts: List[str] = [
            generate_module_header(f"Tests for the {ctx.machine_name}"),
            "# Generated by `xsm generate-template --template pytest`.",
            "# Every assertion below was RECORDED from the real engine when this file",
            "# was generated: the chart was run with stub logic on a SimulatedClock and",
            "# the configuration after each step written down. A failure means the",
            "# chart (or the library) now behaves differently -- not that the",
            "# generator guessed. Regenerate with --force after an intended change.",
            "",
            "from __future__ import annotations",
            "",
            "import json",
            "from pathlib import Path",
            "from typing import Any, Dict, List",
            "",
            "import pytest",
            "",
            "from xstate_statemachine import (",
            "    MachineLogic,",
            "    SimulatedClock,",
            "    SyncInterpreter,",
            "    create_machine,",
            ")",
            "",
            generate_section_header("Machine under test"),
            f"CONFIG_PATH = Path(__file__).with_name({json.dumps(ctx.json_filenames[0])})",
            "",
            "",
            "def load_config() -> Dict[str, Any]:",
            "    return json.loads(CONFIG_PATH.read_text(encoding='utf-8'))",
            "",
            "",
            f"ACTIONS: List[str] = {_py(trace.action_names)}",
            f"GUARDS: List[str] = {_py(trace.guard_names)}",
            f"SERVICES: List[str] = {_py(trace.service_names)}",
            "",
            "",
            "def stub_logic(ran: List[str], guards_pass: bool = True) -> MachineLogic:",
            '    """Stub every implementation: actions record, guards decide, services no-op."""',
            "",
            "    def make_action(name: str):",
            "        def _action(interp, ctx, event, action_def):",
            "            ran.append(name)",
            "",
            "        return _action",
            "",
            "    return MachineLogic(",
            "        actions={a: make_action(a) for a in ACTIONS},",
            "        guards={g: (lambda ctx, event: guards_pass) for g in GUARDS},",
            "        services={s: (lambda interp, ctx, event: None) for s in SERVICES},",
            "    )",
            "",
            "",
            "@pytest.fixture",
            "def ran() -> List[str]:",
            "    return []",
            "",
            "",
            "@pytest.fixture",
            "def clock() -> SimulatedClock:",
            "    return SimulatedClock()",
            "",
            "",
            "@pytest.fixture",
            "def machine(ran: List[str]):",
            "    return create_machine(load_config(), logic=stub_logic(ran))",
            "",
            "",
            "@pytest.fixture",
            "def interp(machine, clock: SimulatedClock):",
            "    i = SyncInterpreter(machine, clock=clock).start()",
            "    yield i",
            "    if i.status == 'running':",
            "        i.stop()",
            "",
            "",
            generate_section_header("Initial state"),
            "def test_initial_state(interp) -> None:",
            f"    assert sorted(interp.current_state_ids) == {_py(trace.initial_state_ids)}",
            "",
            "",
            generate_section_header("Recorded trajectory"),
            "# Each step replays every step before it, so a test is self-contained and",
            "# can be run alone. The recorded sequence is the machine's reachable walk.",
            "",
            "STEPS = [",
        ]
        for s in trace.steps:
            parts.append(
                f"    ({s.kind!r}, {s.event!r}, {s.advance_ms!r}, "
                f"{_py(s.state_ids)}, {_py(s.actions_ran)}),"
            )
        parts += [
            "]",
            "",
            "",
            "def _replay(interp, clock: SimulatedClock, upto: int) -> None:",
            "    for kind, event, advance, _expected, _ran in STEPS[:upto]:",
            "        if kind == 'event':",
            "            interp.send(event)",
            "        else:",
            "            clock.increment(advance)",
            "",
            "",
        ]
        for n, s in enumerate(trace.steps, 1):
            label = safe_identifier(s.event or f"advance_{s.advance_ms}ms")
            parts += [
                f"def test_step_{n:02d}_{label}(interp, clock: SimulatedClock, ran: List[str]) -> None:",
                f"    _replay(interp, clock, {n - 1})",
                "    ran.clear()",
            ]
            if s.kind == "event":
                parts.append(f"    interp.send({s.event!r})")
            else:
                parts.append(f"    clock.increment({s.advance_ms})")
            parts.append(
                f"    assert sorted(interp.current_state_ids) == {_py(s.state_ids)}"
            )
            if s.actions_ran:
                parts.append(f"    assert ran == {_py(s.actions_ran)}")
            parts += ["", ""]

        if trace.final_reached:
            parts += [
                generate_section_header("Completion"),
                "def test_reaches_final_state(interp, clock: SimulatedClock) -> None:",
                "    _replay(interp, clock, len(STEPS))",
                "    assert interp.status == 'done'",
                "",
                "",
            ]

        if trace.guard_names:
            parts += [
                generate_section_header("Guards"),
                "@pytest.fixture",
                "def denied_interp(clock: SimulatedClock):",
                '    """The same machine with every guard returning False."""',
                "    m = create_machine(load_config(), logic=stub_logic([], guards_pass=False))",
                "    i = SyncInterpreter(m, clock=clock).start()",
                "    yield i",
                "    if i.status == 'running':",
                "        i.stop()",
                "",
                "",
                "def test_guarded_transitions_are_denied_when_guards_fail(denied_interp, clock: SimulatedClock) -> None:",
                "    # Walk the recorded sequence; a guarded step must leave the configuration",
                "    # unchanged (or take an unguarded fallback), never crash.",
                "    for kind, event, advance, _expected, _ran in STEPS:",
                "        if kind == 'event':",
                "            receipt = denied_interp.send(event, wait=True)",
                "            assert receipt.error is None",
                "        else:",
                "            clock.increment(advance)",
                "    assert denied_interp.status in ('running', 'done')",
                "",
                "",
            ]

        parts += [
            generate_section_header("Contract"),
            "def test_every_declared_event_is_known(machine) -> None:",
            f"    for event in {_py(trace.events)}:",
            "        assert machine.is_known_event(event)",
            "",
            "",
            "def test_snapshot_round_trip(interp, clock: SimulatedClock, machine) -> None:",
            "    _replay(interp, clock, min(1, len(STEPS)))",
            "    blob = interp.get_snapshot()",
            "    restored = SyncInterpreter.from_snapshot(blob, machine, clock=SimulatedClock())",
            "    assert sorted(restored.current_state_ids) == sorted(interp.current_state_ids)",
            "",
        ]
        if trace.unreached_events:
            parts += [
                "",
                "# Events declared by the chart that the recorded walk never fired -- worth",
                "# a hand-written test each, if they matter to you:",
                *[f"#   - {e}" for e in trace.unreached_events],
                "",
            ]
        return "\n".join(parts)
