# src/xstate_statemachine/cli/strategies/typed.py
# -----------------------------------------------------------------------------
# 🧬 `typed` template -- a types module for a machine
# -----------------------------------------------------------------------------
# Generates, per machine:
#   * `Context` -- a `TypedDict` inferred from the config's initial
#     `context` (int / float / str / bool / list / dict / None → Optional);
#   * `EventType` -- a `Literal[...]` of every event the chart declares;
#   * `StateId` -- a `Literal[...]` of every state id;
#   * typed stubs for every action, guard and service, with the exact
#     signatures the interpreter calls them with;
#   * a `logic()` factory returning a `MachineLogic` bound to the stubs.
# Python 3.9-safe: `typing.Literal` / `TypedDict` exist since 3.8.
# -----------------------------------------------------------------------------
"""The `typed` code-generation strategy."""

from __future__ import annotations

import json
from typing import Any, Dict, List

from ...validation import walk
from ..extractor import extract_logic_names
from ..utils import camel_to_snake
from ._shared import (
    generate_module_header,
    generate_section_header,
    pascal_case_name,
    safe_identifier,
)
from .base import BaseStrategy, GenerationContext


def _annotation(value: Any) -> str:
    if isinstance(value, bool):
        return "bool"
    if isinstance(value, int):
        return "int"
    if isinstance(value, float):
        return "float"
    if isinstance(value, str):
        return "str"
    if isinstance(value, list):
        inner = {_annotation(v) for v in value} or {"Any"}
        return f"List[{inner.pop()}]" if len(inner) == 1 else "List[Any]"
    if isinstance(value, dict):
        return "Dict[str, Any]"
    return "Optional[Any]"


def _literal(values: List[str]) -> str:
    if not values:
        return "str"
    body = ", ".join(json.dumps(v) for v in values)
    return f"Literal[{body}]"


class TypedStrategy(BaseStrategy):
    """Generates a types module: Context TypedDict, event/state Literals,
    typed logic stubs."""

    @property
    def name(self) -> str:
        return "typed"

    def generate_runner(self, ctx: GenerationContext) -> str:
        return ""

    def generate_logic(self, ctx: GenerationContext) -> str:
        config = ctx.configs[0]
        actions, guards, services = extract_logic_names(config)
        # Build once to read the real declared events / state ids.
        from ...factory import create_machine
        from ...machine_logic import MachineLogic

        stub: MachineLogic[Any] = MachineLogic(
            actions={a: (lambda i, c, e, ad: None) for a in actions},
            guards={g: (lambda c, e: True) for g in guards},
            services={s: (lambda i, c, e: None) for s in services},
        )
        machine = create_machine(json.loads(json.dumps(config)), logic=stub)
        events = sorted(
            e
            for e in machine.known_events
            if not e.startswith(("done.", "error.", "after.", "xstate."))
        )
        state_ids = sorted(n.id for n in walk(machine) if n is not machine)
        # 🧭 A Stately export may carry `context` as a JS source STRING
        #    (`"({ spawn }) => ({...})"`); only a JSON object is typeable.
        raw_ctx = config.get("context")
        context: Dict[str, Any] = raw_ctx if isinstance(raw_ctx, dict) else {}
        cls = pascal_case_name(
            camel_to_snake(safe_identifier(ctx.machine_name))
        )

        p: List[str] = [
            generate_module_header(f"Types for the {ctx.machine_name}"),
            "# Generated by `xsm generate-template --template typed`. Import these",
            "# alongside your logic module so actions, guards and services are typed",
            "# against the chart. Regenerate after changing the JSON.",
            "",
            "from __future__ import annotations",
            "",
            "from typing import Any, Dict, List, Literal, Optional, TypedDict, Union",
            "",
            "from xstate_statemachine import (",
            "    ActionDefinition,",
            "    AfterEvent,",
            "    BaseInterpreter,",
            "    DoneEvent,",
            "    ErrorEvent,",
            "    Event,",
            "    MachineLogic,",
            ")",
            "",
            generate_section_header("Vocabulary"),
            f"EventType = {_literal(events)}",
            f"StateId = {_literal(state_ids)}",
            "AnyEvent = Union[Event, DoneEvent, ErrorEvent, AfterEvent]",
            "",
            "",
            generate_section_header("Context"),
        ]
        if context:
            p.append(f"class {cls}Context(TypedDict):")
            p.append(
                f'    """Shape of `context`, inferred from the chart\'s initial value."""'
            )
            p.append("")
            for k, v in context.items():
                p.append(f"    {safe_identifier(k)}: {_annotation(v)}")
        else:
            p.append(
                f"{cls}Context = Dict[str, Any]  # the chart declares no context"
            )
        p += ["", "", generate_section_header("Typed logic stubs"), ""]

        for a in sorted(actions):
            fn = camel_to_snake(safe_identifier(a))
            p += [
                f"def {fn}(",
                f"    interpreter: BaseInterpreter[{cls}Context],",
                f"    context: {cls}Context,",
                "    event: AnyEvent,",
                "    action: ActionDefinition,",
                ") -> None:",
                f'    """Action `{a}`."""',
                "    raise NotImplementedError",
                "",
                "",
            ]
        for g in sorted(guards):
            fn = camel_to_snake(safe_identifier(g))
            p += [
                f"def {fn}(context: {cls}Context, event: AnyEvent) -> bool:",
                f'    """Guard `{g}`."""',
                "    raise NotImplementedError",
                "",
                "",
            ]
        for s in sorted(services):
            fn = camel_to_snake(safe_identifier(s))
            aw = "async " if ctx.is_async else ""
            p += [
                f"{aw}def {fn}(",
                f"    interpreter: BaseInterpreter[{cls}Context],",
                f"    context: {cls}Context,",
                "    event: AnyEvent,",
                ") -> Any:",
                f'    """Service `{s}`."""',
                "    raise NotImplementedError",
                "",
                "",
            ]
        p += [
            generate_section_header("Binding"),
            "def logic() -> MachineLogic:",
            '    """A MachineLogic bound to the stubs above."""',
            "    return MachineLogic(",
            "        actions={"
            + ", ".join(
                f"{json.dumps(a)}: {camel_to_snake(safe_identifier(a))}"
                for a in sorted(actions)
            )
            + "},",
            "        guards={"
            + ", ".join(
                f"{json.dumps(g)}: {camel_to_snake(safe_identifier(g))}"
                for g in sorted(guards)
            )
            + "},",
            "        services={"
            + ", ".join(
                f"{json.dumps(s)}: {camel_to_snake(safe_identifier(s))}"
                for s in sorted(services)
            )
            + "},",
            "    )",
            "",
        ]
        return "\n".join(p)
