# Generated by Django (#310).

import django_fsm
import xstate_statemachine.contrib.django.fields
import xstate_statemachine.contrib.django.fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    django_fsm.FSMField(
                        choices=[
                            ("new", "New"),
                            ("in_progress", "In progress"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="new",
                        max_length=50,
                    ),
                ),
                (
                    "assignee",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "statechart",
                    xstate_statemachine.contrib.django.fields.StatechartField(),
                ),
                (
                    "statechart_state",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=512,
                        null=True,
                    ),
                ),
                (
                    "statechart_state_ids",
                    models.JSONField(blank=True, editable=False, null=True),
                ),
                (
                    "statechart_version",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                (
                    "statechart_machine_version",
                    models.CharField(
                        blank=True, editable=False, max_length=255, null=True
                    ),
                ),
            ],
            options={
                "permissions": [("close_ticket", "Can close tickets")],
            },
            bases=(
                xstate_statemachine.contrib.django.fsm.FSMDualWriteMixin,
                models.Model,
            ),
        ),
    ]
