# Generated by Django 6.1.1 on 2026-10-08 12:37

import django_fsm
import uuid
import xstate_statemachine.contrib.django.fields
import xstate_statemachine.contrib.django.fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legacy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Counter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    django_fsm.FSMIntegerField(
                        choices=[(1, "one"), (2, "two"), (3, "three")],
                        default=1,
                    ),
                ),
                (
                    "statechart",
                    xstate_statemachine.contrib.django.fields.StatechartField(),
                ),
                (
                    "statechart_state",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=512,
                        null=True,
                    ),
                ),
                (
                    "statechart_state_ids",
                    models.JSONField(blank=True, editable=False, null=True),
                ),
                (
                    "statechart_version",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                (
                    "statechart_machine_version",
                    models.CharField(
                        blank=True, editable=False, max_length=255, null=True
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                xstate_statemachine.contrib.django.fsm.FSMDualWriteMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Gadget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    django_fsm.FSMField(
                        choices=[
                            ("in-progress", "In progress"),
                            ("état", "Étatique"),
                            ("1", "One"),
                            ("parked", "Parked"),
                        ],
                        default="in-progress",
                        max_length=50,
                        null=True,
                        protected=True,
                    ),
                ),
                (
                    "chart",
                    xstate_statemachine.contrib.django.fields.StatechartField(),
                ),
                (
                    "chart_state",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=512,
                        null=True,
                    ),
                ),
                (
                    "chart_state_ids",
                    models.JSONField(blank=True, editable=False, null=True),
                ),
                (
                    "chart_version",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                (
                    "chart_machine_version",
                    models.CharField(
                        blank=True, editable=False, max_length=255, null=True
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                xstate_statemachine.contrib.django.fsm.FSMDualWriteMixin,
                models.Model,
            ),
        ),
    ]
