# tests/contrib/sqlalchemy/test_battle_284_b.py
"""#284 battle, adversary B: migrations, schema evolution, StatechartType,
`in_state()` escaping -- on SQLite always, Postgres when reachable
(``DATABASE_URL`` or ``XSM_CONTAINERS=1`` + Docker).

* Alembic for real: the example's migrations from empty, autogenerate
  no-diff, a SECOND team migration autogenerated on top and applied,
  downgrade to base -- on both dialects. Defects fixed: JSONB vs JSON diff
  on Postgres; ``xsm_outbox`` proposed for DROP.
* Schema version: a database written by a newer release is `StoreError`.
* StatechartType: same `SnapshotTooLargeError` on the mixin path as on the
  store path; a corrupt value is `SnapshotCorruptError`; NULL semantics.
* `in_state()` with ``_`` / ``%`` in ids never wildcard-matches.
* xfail(strict) -- found here, owned by store.py / mixin.py (adversary A):
  ``create_tables=False`` on an empty DB; ``statechart_state`` String(512)
  overflow on Postgres for wide parallel charts.
"""

from __future__ import annotations

import json
import os
import shutil
import sys
from pathlib import Path
from typing import Any, Dict, Iterator, Optional

import pytest

from ..conftest import requires_extra

pytestmark = [requires_extra("sqlalchemy"), pytest.mark.timeout(600)]
pytest.importorskip("sqlalchemy")

from sqlalchemy import (  # noqa: E402
    MetaData,
    create_engine,
    insert,
    inspect,
    select,
    text,
    update,
)
from sqlalchemy.orm import (  # noqa: E402
    DeclarativeBase,
    Mapped,
    Session,
    mapped_column,
    sessionmaker,
)

from src.xstate_statemachine import MachineLogic, create_machine  # noqa: E402
from src.xstate_statemachine.contrib.sqlalchemy import (  # noqa: E402
    SCHEMA_VERSION,
    SQLAlchemyOutboxStore,
    SQLAlchemyStore,
    StatechartMixin,
    StatechartType,
    render_statechart_type,
    xsm_sqlalchemy_ddl,
)
from src.xstate_statemachine.contrib.sqlalchemy._schema import (  # noqa: E402
    build_tables,
    check_schema,
    ensure_schema,
)
from src.xstate_statemachine.exceptions import (  # noqa: E402
    SnapshotCorruptError,
    SnapshotTooLargeError,
    StoreError,
)

ROOT = Path(__file__).resolve().parents[3]
EXAMPLE = ROOT / "examples" / "integrations" / "sqlalchemy_orders"
WIDE = 12  # parallel regions with 80-char leaf ids -> > 512 chars
CAP = 16384


# -----------------------------------------------------------------------------
# 🗃️ a model with awkward ids and a wide parallel state
# -----------------------------------------------------------------------------
def _put(i: Any, ctx: Dict[str, Any], e: Any, a: Any) -> None:
    ctx["v"] = e.payload.get("v")


def _chart() -> Dict[str, Any]:
    leaf = "leaf_" + "y" * 40
    regions = {
        f"r{n:02d}_" + "x" * 30: {"initial": leaf, "states": {leaf: {}}}
        for n in range(WIDE)
    }
    return {
        "id": "m_1",
        "initial": "a_b",
        "context": {"v": None},
        "states": {
            "a_b": {"on": {"PUT": {"actions": "put"}, "GO": "pct%"}},
            "axb": {},
            "pct%": {"on": {"WIDE": "wide"}},
            "pctX": {},
            "wide": {"type": "parallel", "states": regions},
        },
    }


class Base(DeclarativeBase):
    pass


class Thing(StatechartMixin, Base):
    __tablename__ = "b284b_things"
    __xsm_machine__ = create_machine(
        _chart(), logic=MachineLogic(actions={"put": _put})
    )
    id: Mapped[int] = mapped_column(primary_key=True)
    statechart: Mapped[Optional[Dict[str, Any]]] = mapped_column(
        StatechartType(max_snapshot_bytes=CAP), nullable=True
    )
    __mapper_args__ = StatechartMixin.optimistic()


xsm_sqlalchemy_ddl(Base.metadata)


# -----------------------------------------------------------------------------
# 🔌 engines
# -----------------------------------------------------------------------------
def _pg_env() -> Optional[str]:
    url = os.environ.get("DATABASE_URL", "")
    return url if url.startswith("postgresql") else None


@pytest.fixture(scope="module")
def pg_container_url() -> Iterator[Optional[str]]:
    if _pg_env() or os.environ.get("XSM_CONTAINERS") != "1":
        yield None
        return
    tc = pytest.importorskip("testcontainers.postgres")
    pytest.importorskip("psycopg")
    with tc.PostgresContainer("postgres:16-alpine", driver="psycopg") as pg:
        yield pg.get_connection_url()


@pytest.fixture(params=["sqlite", "postgres"])
def url(request: Any, tmp_path: Path, pg_container_url: Any) -> Iterator:
    if request.param == "sqlite":
        yield f"sqlite:///{(tmp_path / 'b.db').as_posix()}"
        return
    u = _pg_env() or pg_container_url
    if not u:
        pytest.skip("no Postgres: set DATABASE_URL or XSM_CONTAINERS=1")
    _wipe(u)
    yield u
    _wipe(u)


def _wipe(u: str) -> None:
    eng = create_engine(u)
    try:
        md = MetaData()
        md.reflect(eng)
        md.drop_all(eng)
    finally:
        eng.dispose()


@pytest.fixture
def engine(url: str) -> Iterator[Any]:
    eng = create_engine(url)
    Base.metadata.create_all(eng)
    try:
        yield eng
    finally:
        eng.dispose()


def _new(eng: Any) -> int:
    with Session(eng) as s:
        t = Thing()
        s.add(t)
        s.commit()
        return t.id


def _send(eng: Any, tid: int, event: str, **payload: Any) -> None:
    with Session(eng) as s:
        s.get(Thing, tid).send(event, session=s, **payload)
        s.commit()


def _ids_in(eng: Any, *sids: str) -> list:
    with Session(eng) as s:
        return list(s.scalars(select(Thing.id).where(Thing.in_state(*sids))))


# -----------------------------------------------------------------------------
# 1. Alembic for real, both dialects
# -----------------------------------------------------------------------------
def _alembic(url: str, script_dir: Path) -> Any:
    from alembic.config import Config

    cfg = Config(str(EXAMPLE / "alembic.ini"))
    cfg.set_main_option("script_location", str(script_dir))
    cfg.set_main_option("sqlalchemy.url", url)
    cfg.attributes["configure_logger"] = False
    return cfg


@pytest.fixture
def example_models() -> Iterator[Any]:
    """The example's `models`, imported from ITS directory and left in
    `sys.modules` for the test (env.py's `from models import Base` must
    bind the SAME metadata object the test mutates); another example's
    same-named modules (fastapi_orders, flask_wizard -- CI's Coverage job
    runs them all in one process) are set aside and restored after."""
    import importlib

    names = ("logic", "models")
    saved = {k: sys.modules.pop(k) for k in names if k in sys.modules}
    sys.path.insert(0, str(EXAMPLE))
    try:
        importlib.import_module("logic")
        models = importlib.import_module("models")
        yield models
    finally:
        sys.path.remove(str(EXAMPLE))
        for k in names:
            sys.modules.pop(k, None)
        sys.modules.update(saved)


def _diff(url: str, metadata: Any) -> list:
    from alembic.autogenerate import compare_metadata
    from alembic.migration import MigrationContext

    eng = create_engine(url)
    try:
        with eng.connect() as conn:
            return compare_metadata(MigrationContext.configure(conn), metadata)
    finally:
        eng.dispose()


def test_alembic_upgrade_no_diff_second_migration_downgrade(
    url: str, tmp_path: Path, monkeypatch: pytest.MonkeyPatch, example_models
) -> None:
    pytest.importorskip("alembic")
    from alembic import command
    from sqlalchemy import Column, String

    monkeypatch.setenv("ORDERS_DB_URL", url)
    mig = tmp_path / "migrations"
    shutil.copytree(
        EXAMPLE / "migrations",
        mig,
        ignore=shutil.ignore_patterns("__pycache__"),
    )
    models = example_models
    cfg = _alembic(url, mig)
    command.upgrade(cfg, "head")
    eng = create_engine(url)
    try:
        cols = {c["name"]: c for c in inspect(eng).get_columns("orders")}
        kind = type(cols["statechart"]["type"]).__name__
        assert kind == ("JSONB" if url.startswith("postgresql") else "JSON")
        # 🔥 the outbox store creating its table must not make a diff
        store = SQLAlchemyStore(sessionmaker(eng), metadata=MetaData())
        SQLAlchemyOutboxStore(store)
    finally:
        eng.dispose()
    assert _diff(url, models.Base.metadata) == []
    # -- the team's next migration: a column on orders, autogenerated
    orders = models.Base.metadata.tables["orders"]
    orders.append_column(Column("coupon", String(40), nullable=True))
    try:
        command.revision(cfg, "coupon", autogenerate=True, rev_id="0004")
        [new] = list((mig / "versions").glob("0004_*.py"))
        body = new.read_text("utf-8")
        assert "add_column" in body and "coupon" in body
        assert "drop_table" not in body and "alter_column" not in body
        command.upgrade(cfg, "head")
        assert _diff(url, models.Base.metadata) == []
        command.downgrade(cfg, "0003")
    finally:
        orders._columns.remove(orders.c.coupon)
    assert _diff(url, models.Base.metadata) == []
    command.downgrade(cfg, "base")
    eng = create_engine(url)
    try:
        assert set(inspect(eng).get_table_names()) <= {"alembic_version"}
    finally:
        eng.dispose()


def test_render_item_hook_renders_the_variant() -> None:
    class Ctx:
        imports: set = set()

    ctx = Ctx()
    out = render_statechart_type("type", StatechartType(), ctx)
    assert out == 'sa.JSON().with_variant(postgresql.JSONB(), "postgresql")'
    assert "from sqlalchemy.dialects import postgresql" in ctx.imports
    assert render_statechart_type("type", MetaData(), ctx) is False


def test_ddl_helper_covers_the_outbox() -> None:
    md = xsm_sqlalchemy_ddl(MetaData())
    assert "xsm_outbox" in md.tables and "xsm_deadlines" in md.tables


# -----------------------------------------------------------------------------
# 2. schema version (X0.10)
# -----------------------------------------------------------------------------
def test_newer_schema_is_refused(engine: Any) -> None:
    tables = build_tables(MetaData())
    with engine.begin() as conn:
        assert ensure_schema(conn, tables) == SCHEMA_VERSION
        conn.execute(update(tables.schema).values(version=SCHEMA_VERSION + 1))
    with engine.begin() as conn:
        with pytest.raises(StoreError, match="newer than this library"):
            ensure_schema(conn, tables)
        with pytest.raises(StoreError, match="newer than this library"):
            check_schema(conn, tables)
    with pytest.raises(StoreError, match="newer"):
        SQLAlchemyStore(sessionmaker(engine), create_tables=False)


def test_check_schema_on_empty_db_is_a_clear_error(url: str) -> None:
    eng = create_engine(url)
    try:
        with eng.begin() as conn:
            with pytest.raises(StoreError, match="Run your migrations"):
                check_schema(conn, build_tables(MetaData()))
    finally:
        eng.dispose()


def test_store_create_tables_false_on_empty_db(url: str) -> None:
    eng = create_engine(url)
    try:
        with pytest.raises(StoreError, match="Run your migrations"):
            SQLAlchemyStore(sessionmaker(eng), create_tables=False)
    finally:
        eng.dispose()


# -----------------------------------------------------------------------------
# 3. StatechartType
# -----------------------------------------------------------------------------
def test_type_is_cacheable_and_values_stay_dicts(engine: Any) -> None:
    assert StatechartType.cache_ok is True
    tid = _new(engine)
    _send(engine, tid, "PUT", v=1)
    with Session(engine) as s:
        row = s.get(Thing, tid)
        assert isinstance(row.statechart, dict)  # lazy: no interpreter
        assert row.machine.context["v"] == 1


def test_size_cap_same_error_on_mixin_and_store(engine: Any) -> None:
    tid = _new(engine)
    with Session(engine) as s:
        with pytest.raises(SnapshotTooLargeError) as mixin_exc:
            s.get(Thing, tid).send("PUT", session=s, v="x" * (CAP + 1))
    store = SQLAlchemyStore(sessionmaker(engine), max_snapshot_bytes=CAP)
    with pytest.raises(SnapshotTooLargeError) as store_exc:
        store.save("k", "x" * (CAP + 1))
    assert type(store_exc.value) in type(mixin_exc.value).__mro__
    assert mixin_exc.value.limit == store_exc.value.limit == CAP


def test_corrupt_column_is_snapshot_corrupt(engine: Any) -> None:
    tid = _new(engine)
    _send(engine, tid, "PUT", v=1)
    with engine.begin() as conn:  # valid JSON, not an object
        conn.execute(
            text("UPDATE b284b_things SET statechart = :v WHERE id = :i"),
            {"v": json.dumps([1, 2]), "i": tid},
        )
    with Session(engine) as s:
        with pytest.raises(SnapshotCorruptError):
            s.get(Thing, tid)
    if engine.dialect.name == "sqlite":  # JSONB would refuse to store it
        with engine.begin() as conn:
            conn.execute(
                text("UPDATE b284b_things SET statechart = '{nope' "),
            )
        with Session(engine) as s:
            with pytest.raises(SnapshotCorruptError, match="invalid JSON"):
                s.get(Thing, tid)


def test_writing_a_non_dict_is_type_error(engine: Any) -> None:
    from sqlalchemy import Column, Integer, Table

    t = Table(
        "b284b_raw",
        MetaData(),
        Column("id", Integer, primary_key=True),
        Column("sc", StatechartType()),
    )
    t.create(engine)
    with engine.begin() as conn:
        with pytest.raises(TypeError, match="snapshot dict"):
            conn.execute(insert(t).values(id=1, sc=[1]))


def test_null_statechart_semantics(engine: Any) -> None:
    tid = _new(engine)
    with Session(engine) as s:
        row = s.get(Thing, tid)
        assert row.statechart is None and row.state is None
        assert row.statechart_state_ids is None
    assert _ids_in(engine, "m_1", "m_1.a_b") == []
    _send(engine, tid, "PUT", v=1)  # starts from the initial state
    assert _ids_in(engine, "m_1.a_b") == [tid]


def test_non_json_context_values_are_stringified(engine: Any) -> None:
    """Pins today's core behaviour (`get_snapshot` uses ``default=str``):
    a datetime / Decimal / set survives a save as its ``str()``. Loud
    would be better; it is core-wide, not [sqlalchemy]-specific."""
    import datetime
    import decimal

    tid = _new(engine)
    for v in (datetime.date(2026, 1, 2), decimal.Decimal("1.50"), {7}):
        _send(engine, tid, "PUT", v=v)
        with Session(engine) as s:
            assert s.get(Thing, tid).machine.context["v"] == str(v)


# -----------------------------------------------------------------------------
# 5. in_state() escaping
# -----------------------------------------------------------------------------
def test_in_state_treats_underscore_and_percent_literally(engine: Any):
    a = _new(engine)
    _send(engine, a, "PUT", v=1)  # m_1.a_b
    b = _new(engine)
    _send(engine, b, "GO")  # m_1.pct%
    assert _ids_in(engine, "m_1.a_b") == [a]
    assert _ids_in(engine, "m_1.axb") == []  # `_` is not a wildcard
    assert _ids_in(engine, "m_1.a%") == []  # `%` is not a wildcard
    assert _ids_in(engine, "m_1.pct%") == [b]
    assert _ids_in(engine, "m_1.pctX") == []
    assert _ids_in(engine, "m_1.pct") == []
    assert _ids_in(engine, "m_1") == [a, b]  # ancestor
    assert _ids_in(engine, "m_") == []
    assert sorted(_ids_in(engine, "m_1.a_b", "m_1.pct%")) == [a, b]


# -----------------------------------------------------------------------------
# 2b. statechart_state for wide parallel charts (> 512 chars)
# -----------------------------------------------------------------------------
def test_wide_parallel_state_round_trips(engine: Any, url: str) -> None:
    tid = _new(engine)
    _send(engine, tid, "GO")
    try:
        _send(engine, tid, "WIDE")
    except Exception as exc:  # 🔥 Postgres: StringDataRightTruncation
        if not url.startswith("postgresql"):
            raise
        pytest.xfail(
            "mixin.py (adversary A): statechart_state is String(512); "
            f"Postgres refuses a wide parallel chart ({type(exc).__name__})"
            ", SQLite stores it -- make it Text"
        )
    with Session(engine) as s:
        row = s.get(Thing, tid)
        assert len(row.state) > 512
        assert len(row.statechart_state_ids) == WIDE
    assert _ids_in(engine, "m_1.wide") == [tid]


def test_raw_insert_of_schema_row_roundtrip(engine: Any) -> None:
    tables = build_tables(MetaData())
    with engine.begin() as conn:
        ensure_schema(conn, tables)
        ensure_schema(conn, tables)  # idempotent
        n = conn.execute(select(tables.schema.c.version)).all()
    assert n == [(SCHEMA_VERSION,)]
    with engine.begin() as conn:
        with pytest.raises(Exception):
            conn.execute(
                insert(tables.schema).values(component="sqlalchemy", version=1)
            )


# -----------------------------------------------------------------------------
# 4. docs truth
# -----------------------------------------------------------------------------
def test_docs_name_every_public_member_and_no_stale_outbox_claim() -> None:
    import src.xstate_statemachine.contrib.sqlalchemy as pkg

    guide = (ROOT / "docs/_guide/integration-sqlalchemy.md").read_text("utf-8")
    api = (ROOT / "docs/api/index.md").read_text("utf-8")
    row = next(
        ln for ln in api.splitlines() if ln.startswith("| `[sqlalchemy]`")
    )
    for name in pkg.__all__:
        assert f"`{name}" in guide or name == "SCHEMA_VERSION", name
        assert f"`{name}`" in row, name
    for stale in ("arrives with #293", "pretends to publish", "0.12"):
        assert stale not in guide, stale
    assert "at-least-once" in guide and "integration-eda" in guide
    readme = (EXAMPLE / "README.md").read_text("utf-8")
    assert "publishes nothing and does not pretend" not in readme
