#!/usr/bin/env python
# scripts/gen_compatibility.py
# -----------------------------------------------------------------------------
# 🧮 Framework-compatibility table (#296)
# -----------------------------------------------------------------------------
# ONE source of truth, tests/contrib/compat_matrix.json, feeds three things:
#
#   python scripts/gen_compatibility.py            -> docs/_guide/compatibility.md
#   python scripts/gen_compatibility.py --check    -> exit 1 if the page drifted
#   python scripts/gen_compatibility.py --matrix   -> the CI cells (JSON)
#   python scripts/gen_compatibility.py --pip-args EXTRA oldest|newest
#                                                  -> what that cell installs
#
# 🏛️ The compat workflow builds its matrix from `--matrix` and installs with
#    `--pip-args`, so the table cannot promise a version no cell tested.
#    Standard library only; Windows-safe (always writes "\n").
# -----------------------------------------------------------------------------
"""Generate the compatibility page and CI matrix from compat_matrix.json."""

from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys
from typing import Any, Dict, List

ROOT = pathlib.Path(__file__).resolve().parents[1]
MATRIX = ROOT / "tests" / "contrib" / "compat_matrix.json"
PAGE = ROOT / "docs" / "_guide" / "compatibility.md"
KINDS = ("oldest", "newest")

HEADER = """\
---
title: "Compatibility"
description: "Framework versions each extra is tested against -- oldest and newest, each proven by a CI cell."
---

<!-- GENERATED by scripts/gen_compatibility.py from tests/contrib/compat_matrix.json -- do not edit by hand. -->

# Compatibility

Every **shipped** extra is tested against two versions of the framework it
integrates with:

- the **oldest** release proven to pass the extra's test suite, pinned exactly,
  on the **oldest** supported Python (3.9), and
- the **newest** release the resolver picks, on a current Python.

Both cells run in the `compat` workflow (weekly, on demand, and on every pull
request that changes `pyproject.toml` or the matrix). This page is generated
from the same file the workflow reads, so a version listed here is a version
a CI cell installed and tested.

**Declared** is the lower bound in `pyproject.toml`, which is what pip will
accept. Where **oldest tested** is higher, older releases in that range were
probed and do not pass on Python 3.9. The reason is in the notes. Treat the
tested version as the practical minimum.

| Extra | Framework | Declared | Oldest tested | Newest tested | Also pinned in the oldest cell |
|:--|:--|:--|:--|:--|:--|
"""

FOOTER = """
The core library has **no runtime dependencies** and supports **Python 3.9 to
3.14**. Extras not listed here are placeholders that install nothing yet. See
[Integrations & extras](../integrations-extras/). How versions and
deprecations are managed is on the [Deprecation Policy](../deprecation-policy/)
page. `contrib` APIs are provisional.
"""


def load() -> Dict[str, Dict[str, Any]]:
    data = json.loads(MATRIX.read_text(encoding="utf-8"))
    extras: Dict[str, Dict[str, Any]] = data["extras"]
    return extras


def _version(spec: str) -> str:
    for op in ("==", ">="):
        if op in spec:
            return op.replace("==", "") + spec.split(op, 1)[1]
    return spec


def verified() -> str:
    data = json.loads(MATRIX.read_text(encoding="utf-8"))
    return str(data.get("verified", "unknown"))


def render(extras: Dict[str, Dict[str, Any]]) -> str:
    rows: List[str] = []
    notes: List[str] = []
    for name in sorted(extras):
        e = extras[name]
        pins = ", ".join(f"`{p}`" for p in e.get("extra_pins", [])) or "--"
        mark = ""
        if e.get("note"):
            notes.append(f"- **`[{name}]`**: {e['note']}")
            mark = " (see notes)"
        rows.append(
            f"| `[{name}]` | {e['package']} | `>={e['declared']}` "
            f"| **{_version(e['oldest'])}**{mark} "
            f"(Python {e['python']['oldest']}) "
            f"| latest `{e['newest']}` (Python {e['python']['newest']}) "
            f"| {pins} |"
        )
    body = HEADER + "\n".join(rows) + "\n"
    if notes:
        body += "\n### Notes\n\n" + "\n".join(notes) + "\n"
    stamp = (
        "\nThis table is generated and asserted, not hand-written:\n"
        "`tests/test_compat_matrix.py` fails if the page drifts from the\n"
        "matrix or the matrix from `pyproject.toml`, and the compat\n"
        "workflow installs exactly these pins. Matrix verified: "
        f"{verified()}.\n"
    )
    return body + stamp + FOOTER


def matrix(extras: Dict[str, Dict[str, Any]]) -> List[Dict[str, str]]:
    return [
        {"extra": name, "kind": kind, "python": extras[name]["python"][kind]}
        for name in sorted(extras)
        for kind in KINDS
    ]


#: What every cell needs to RUN the suite. A runner package the cell pins
#: itself is left out (the [testing] extra IS pytest; a second, newer floor
#: would make its oldest cell unsatisfiable).
RUNNER = ("pytest>=8.3.0", "pytest-asyncio>=0.24.0", "pytest-socket>=0.7")


def _dist(spec: str) -> str:
    return re.split(r"[\[<>=!~ ]", spec, maxsplit=1)[0].lower()


def pip_args(
    extras: Dict[str, Dict[str, Any]], name: str, kind: str
) -> List[str]:
    e = extras[name]
    args = [f".[{name}]", e[kind]]
    if kind == "oldest":
        args += list(e.get("extra_pins", []))
    args += list(e.get("test_deps", []))
    pinned = {_dist(a) for a in args if "==" in a}
    args += [r for r in RUNNER if _dist(r) not in pinned]
    return args


def main(argv: List[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--matrix", action="store_true")
    ap.add_argument("--pip-args", nargs=2, metavar=("EXTRA", "KIND"))
    ns = ap.parse_args(argv)
    extras = load()
    if ns.matrix:
        print(json.dumps({"include": matrix(extras)}))
        return 0
    if ns.pip_args:
        name, kind = ns.pip_args
        if name not in extras or kind not in KINDS:
            print(f"unknown cell {name}/{kind}", file=sys.stderr)
            return 2
        print("\n".join(pip_args(extras, name, kind)))
        return 0
    text = render(extras)
    if ns.check:
        # 📝 Compare CONTENT, not bytes: a Windows checkout with autocrlf
        #    reads the committed page back with CRLF and would call an
        #    up-to-date page stale. CI (LF) is unaffected either way.
        current = PAGE.read_text(encoding="utf-8") if PAGE.exists() else ""
        if current.replace("\r\n", "\n") != text:
            print(f"{PAGE} is stale; run scripts/gen_compatibility.py")
            return 1
        print("compatibility.md is up to date")
        return 0
    with open(PAGE, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    print(f"wrote {PAGE.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
