# src/xstate_statemachine/cli/commands/docs.py
# -----------------------------------------------------------------------------
# 📄 `xsm docs` -- a Markdown page per machine
# -----------------------------------------------------------------------------
"""Generate reference documentation for a machine: summary, Mermaid
diagram, state table, transition table, logic to implement, policies."""

from __future__ import annotations

from pathlib import Path
from typing import List, Optional

from ...validation import walk
from . import get_console
from .analysis import Facts, analyse, event_table
from .inspect import _policies


def _md_escape(s: str) -> str:
    return s.replace("|", "\\|")


def render_markdown(facts: Facts) -> str:
    m = facts.machine
    assert m is not None
    total = facts.state_count(all_levels=True)
    out: List[str] = [
        f"# `{m.id}`",
        "",
        f"> Generated by `xsm docs` from `{facts.path.name}`. "
        f"{total} states · {len(facts.events)} events · "
        f"{len(facts.actions)} actions · {len(facts.guards)} guards · "
        f"{len(facts.services)} services.",
        "",
        "## Diagram",
        "",
        "```mermaid",
        m.to_mermaid(),
        "```",
        "",
        "## States",
        "",
        "| State | Kind | Initial | Entry | Exit | Timers | Invokes | Tags |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for n in walk(m):
        if n is m:
            continue
        out.append(
            "| `{}` | {} | {} | {} | {} | {} | {} | {} |".format(
                n.id,
                n.type,
                f"`{n.initial}`" if n.initial else "",
                ", ".join(f"`{a.type}`" for a in n.entry) or "",
                ", ".join(f"`{a.type}`" for a in n.exit) or "",
                ", ".join(str(k) for k in n.after) or "",
                ", ".join(f"`{i.src}`" for i in n.invoke) or "",
                ", ".join(f"`{t}`" for t in sorted(n.tags)) or "",
            )
        )
    out += [
        "",
        "## Transitions",
        "",
        "| Event | From | To | Guard | Actions |",
        "|---|---|---|---|---|",
    ]
    for ev, src, dst, guard, acts in event_table(m):
        out.append(
            f"| `{_md_escape(ev)}` | `{src}` | `{dst}` | "
            f"{'`' + guard + '`' if guard else ''} | "
            f"{', '.join('`' + a.strip() + '`' for a in acts.split(',')) if acts else ''} |"
        )
    out += ["", "## Logic to implement", ""]
    for kind, names in (
        ("Actions", facts.actions),
        ("Guards", facts.guards),
        ("Services", facts.services),
        ("Named delays", facts.delays),
    ):
        if names:
            out.append(
                f"**{kind}:** " + ", ".join(f"`{n}`" for n in sorted(names))
            )
            out.append("")
    out += ["## Policies", "", "| Key | Value |", "|---|---|"]
    for k, v in _policies(m):
        out.append(f"| `{k}` | `{v}` |")
    warnings = [f for f in facts.findings if f.severity == "warning"]
    if warnings:
        out += ["", "## Warnings", ""]
        for w in warnings:
            out.append(f"- {w.message}" + (f" (`{w.path}`)" if w.path else ""))
    out += [
        "",
        "## Events",
        "",
        ", ".join(f"`{e}`" for e in sorted(facts.events)),
        "",
    ]
    return "\n".join(out)


def run_docs(paths: List[str], *, output: Optional[str] = None) -> None:
    c = get_console()
    written = 0
    failed = 0
    for p in paths:
        facts = analyse(Path(p), strict_config=False)
        if facts.machine is None:
            # 📚 One broken file in `machines/*.json` must not stop the
            #    others from being documented; report it, carry on, and
            #    exit 1 at the end.
            for f in facts.findings:
                c.error(f"{p}: {f.message}")
            failed += 1
            continue
        md = render_markdown(facts)
        if output is None:
            c.print(md)
            continue
        out_dir = Path(output)
        out_dir.mkdir(parents=True, exist_ok=True)
        target = out_dir / f"{facts.machine_id}.md"
        target.write_text(md, encoding="utf-8")
        c.ok(f"Wrote {c.style(str(target), 'path')}")
        written += 1
    if output is not None:
        c.print(c.style(f"{written} page(s) written to {output}", "muted"))
    if failed:
        c.error(f"{failed} file(s) could not be documented")
        raise SystemExit(1)
